apiVersion: skaffold/v4beta12
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: dushyantkumarsingh/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: dushyantkumarsingh/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "**/*.ts"
    - image: dushyantkumarsingh/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: dushyantkumarsingh/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: dushyantkumarsingh/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: dushyantkumarsingh/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"